# Generated by Django 4.2.3 on 2023-08-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LINEFollower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=100)),
                ('mode', models.CharField(max_length=15)),
                ('stamp', models.CharField(max_length=200)),
            ],
        ),
    ]
